### ISSUE TITLE
Customize Bracket Matching Colors

### ISSUE THREAD

**Issue by wunderman4** [loilo/vscode-snazzy-light#4]
Hello, 

First I want to say that I'm a huge fan of snazzy light, it's my go-to theme 99% of the time. With the latest 1.6 release of vscode  (https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_60.md#high-performance-bracket-pair-colorization) there is now bracket syntax highlighting built-in. It looks like there is an ability to use workbench.colorCustomizations to override the bracket matching colors. 

It would be cool if the snazzy-light theme included colors for the brackets. Right now they default to what looks like the stock vscode light theme colors.

**Comment by loilo** [comment]
Sorry for coming back to you so late, I seem to accidentally have turned off the repository's notifications. 🙈 

I'm really glad you like the theme. ❤️ 

Regarding your suggestion: What kind of colors would you prefer for the brackets?

You're right that it's currently using VSCode stock colors. I have thought about defining a custom set of bracket colors, but I'm not really sure if that provides any real value — the stock colors are quite drastic, and I think that's what they should be to really highlight bracket paris. Therefore I can't really resort to just using the theme's colors for matching brackets, as that would defeat the purpose of the feature.

That said, it's easy for me to say "just use stock colors" because I don't have the matching brackets feature enabled by default (can't stand the eye-catching colors); I use [Settings Cycler](https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler) with a custom hotkey to toggle the feature on demand.

**Comment by wunderman4** [comment]
Hey no worries, I like your idea to use Settings Cycler I will take a look and see if it works for me as well. Since the time I submitted this, I've honestly gone blind to the brackets at this point so I will close it out.  

The idea I had for the bracket colors was more along the lines of shifting the stock colors saturation/hue have less contrast with the theme, but again, I'm not worried about it, still love the theme ❤️
